permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "Dolphin"
email: "zlfbasic@gmail.com"
description: "Developer"
github_username:  "mastery001"
swiftype_searchId: "osWCmLmKVCq1AQZfHfVh"
disqus_shortname: "mastery"



url: "http://mastery001.github.io"
imgrepo: "http://mastery001.github.io/static/img"


#url: "http://10.58.88.155:4000"
#imgrepo: "http://10.58.88.155:4000/static/img"
#gems: [jekyll-paginate]

