permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "James VenZ"
email: "zlfbasic@gmail.com"
description: "Blog"
github_username:  "mastery001"
swiftype_searchId: "osWCmLmKVCq1AQZfHfVh"
disqus_shortname: "mastery"

excerpt_separator: <!--more-->


url: "http://blog.ziwenzou.com"
imgrepo: "http://blog.ziwenzou.com/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
#gems: [jekyll-paginate]


